####################################################################
#
# Makefile include flags, you add all the flags here
#
####################################################################

CC := g++
CFLAGS := -c 
OFLAG := -o
PIC := -fPIC 
DEBUG := -g
AR_FLAG : = rvs
AR : = ar

LD_FLAGS := -l

COPY := cp
COPY_DIR_FLAG := -rf

C++11 := -std=c++11 
C++14 := -std=c++14 
