#!/bin/bash

############################################
# create 10 cpp files
# one main file add simple helloWorld
############################################
oldDir=`pwd`
cd exe
for i in `seq 1 10`;
do
	touch testExe_$i.cpp;
done


echo -e "#include<iostream>\nusing namespace std;\nint main() {\n return 0;\n}" > testExe_1.cpp
cd $oldDir

############################################
# create 10 cpp files to create shared library
############################################
oldDir=`pwd`
cd shared-object
for i in `seq 1 10`;
do
	touch testShared_$i.cpp;
done
cd $oldDir

############################################
# create 10 cpp files for static library
############################################
oldDir=`pwd`
cd static-library
for i in `seq 1 10`;
do
	touch testStatic_$i.cpp;
done
cd $oldDir
